### ISSUE TITLE
Plugy 14.02 out

### ISSUE THREAD

**Issue by crashinz** [ChaosMarc/D2VersionChanger#3]
Hi, not an issue with your version changer but a bug was fixed with plugy that let you have multiple unique charms whenever you want to update your program.
in mean time people can just replace these files:
PlugY.dll
PlugY.exe
PlugY.ini
PlugY\LocalizedStrings.ini
PlugY\PlugYDefault.ini
PlugY\PlugYFixed.ini

**Comment by ChaosMarc** [comment]
Thank you for reminding me. I've created release v4.6 with PlugY 14.02: https://github.com/ChaosMarc/D2VersionChanger/releases/tag/v4.6
