### ISSUE TITLE
weird letter and number on top left of screen

### ISSUE THREAD

**Issue by HuskyKing1056** [ChaosMarc/D2VersionChanger#4]
there are are weird letter and number on the top left of my screen playing while launching 1.13c, should i be concerned

**Comment by ChaosMarc** [comment]
This is a standard "feature" of Diablo in all versions before 1.14. It's some kind of font-check. Most of the time the startup is so fast that you can't see the characters running in the corner. If you startup is slow, perhaps switching the video mode could help. I use Sven's GlideWrapper: https://www.svenswrapper.de/english/downloads.html
